---
title: "Practice-3"
author: "Harsh"
date: "25/05/2020"
output: html_document
---

```{r}

library(data.table)

cancer_data <- read.csv("C:\\Users\\harsh\\Desktop\\Introduction to Machine learning and Data Mining\\Practice 3\\prostate_cancer.csv", header = TRUE, stringsAsFactors = FALSE)

head(cancer_data)

cancer_data_1 <- cancer_data

cancer_data_1 <- cancer_data_1[-1]

setDT(cancer_data_1)

normalize <- function(x){
  return((x - min(x)) / (max(x) - min(x)))
}

str(cancer_data_1)

cancer_data_1 <- as.data.frame(lapply(cancer_data[,3:9],normalize))

summary(cancer_data_1)

training_data <- cancer_data_1[1:65,]
testing_data <- cancer_data_1[66:100,]

training_data_labels <- cancer_data[1:65,2]
testing_data_labels <- cancer_data[66:100,2]

```


```{r}

#install.packages("class")
#install.packages("gmodels")

library(class)
library(gmodels)

cancer_pred <- knn(train = training_data, test = testing_data, cl = training_data_labels, k = 6)

CrossTable(x = testing_data_labels, y = cancer_pred, prop.chisq = FALSE)

```


```{r}

#install.packages("caret")
library(caret)

cancer_data$diagnosis_result <- as.factor(cancer_data$diagnosis_result)

set.seed(123)

train.cancer <- training_data
train.cancer$diagnosis_result <- as.factor(training_data_labels)
test.cancer <- testing_data
test.cancer$diagnosis_result <- as.factor(testing_data_labels)

trctrl <- trainControl(method = "repeatedcv", number = 10, repeats = 3)

knn_fit <- train(diagnosis_result ~., data = train.cancer, method = "knn",
                 trControl=trctrl,
                 preProcess = c("center", "scale"),
                 tuneLength = 10)

knn_fit

plot(knn_fit)

test_pred <- predict(knn_fit, newdata = test.cancer)
test_pred

confusionMatrix(test_pred, test.cancer$diagnosis_result )

confusionMatrix(cancer_pred, testing_data_labels1)

```


