---
title: "Practicum-3.2"
author: "Harsh"
date: "26/07/2020"
output: pdf_document
---
```{r}

library(arules)

```

```{r}

plant_data <- read.transactions("C:\\Users\\harsh\\Desktop\\Introduction to Machine learning and Data Mining\\Practicum-3\\plants.data", sep = ",")

summary(plant_data)

inspect(plant_data[1:5])

```


```{r}

itemFrequency(plant_data[,1:5])
itemFrequencyPlot(plant_data[,1:5],support = 0.1)
itemFrequencyPlot(plant_data,topN=20)

image(plant_data[1:15000])
image(sample(plant_data[1:15000]))

```


```{r}

default_rules <- apriori(plant_data)
summary(default_rules)
inspect(default_rules[1:5])

new_rules <- apriori(plant_data, parameter = list (support = 0.001, confidence = 0.75))
summary(new_rules)
inspect(new_rules[1:5])

```


```{r}
plants <- read.transactions("C:\\Users\\harsh\\Desktop\\Introduction to Machine learning and Data Mining\\Practicum-3\\plants.data", sep = ",", cols = 1)

summary(plants)

plants_matrix <- as.data.frame(as(plants,"matrix"))

plants_matrix[,1:70] <- lapply(plants_matrix[,1:70],as.integer)

str(plants_matrix)

clusters <- kmeans(plants_matrix,8)
clusters$size
clusters$centers

fpc::plotcluster(plants_matrix,clusters$cluster)


```
Reference: 
https://stats.stackexchange.com/questions/31083/how-to-produce-a-pretty-plot-of-the-results-of-k-means-cluster-analysis
https://stackoverflow.com/questions/41972270/how-to-convert-object-of-transaction-to-dataframe-in-r






