---
title: "Practice-7"
author: "Harsh"
date: "11/07/2020"
output: pdf_document
---


```{r}

#install.packages("neuralnet")
#install.packages("arules")
library(neuralnet)
library(kernlab)
library(arules)

```



```{r}

concrete_data <- read.csv("C:\\Users\\harsh\\Desktop\\Introduction to Machine learning and Data Mining\\Practice 7\\concrete.csv")

head(concrete_data)

str(concrete_data)

```


```{r}

normalize <- function(x) {
  return((x - min(x)) / (max(x) - min(x)))
}

concrete_norm <- as.data.frame(lapply(concrete_data, normalize))

summary(concrete_norm$strength)
summary(concrete_data$strength)

```


```{r}

concrete_train <- concrete_norm[1:773, ]
concrete_test <- concrete_norm[774:1030, ]

concrete_model <- neuralnet(strength ~ cement + slag + ash + water + superplastic + coarseagg + fineagg + age, data = concrete_train)

plot(concrete_model)

model_results <- compute(concrete_model, concrete_test[1:8])

predicted_strength <- model_results$net.result

cor(predicted_strength, concrete_test$strength)

concrete_model2 <- neuralnet(strength ~ cement + slag + ash + water + superplastic + coarseagg + fineagg + age,data = concrete_train, hidden = 5)

plot(concrete_model2)

model_results2 <- compute(concrete_model2, concrete_test[1:8])

predicted_strength2 <- model_results2$net.result

cor(predicted_strength2, concrete_test$strength)

```


```{r}


letters_data <- read.csv("C:\\Users\\harsh\\Desktop\\Introduction to Machine learning and Data Mining\\Practice 7\\letterdata.csv")

head(letters_data)

str(letters_data)

letters_train <- letters_data[1:16000, ]
letters_test <- letters_data[16001:20000, ]

letter_classifier <- ksvm(letter ~ ., data = letters_train,
kernel = "vanilladot")

letter_classifier

letter_predictions <- predict(letter_classifier, letters_test)

head(letter_predictions)

table(letter_predictions, letters_test$letter)

agreement <- letter_predictions == letters_test$letter

table(agreement)

prop.table(table(agreement))

letter_classifier_rbf <- ksvm(letter ~ ., data = letters_train,
kernel = "rbfdot")

letter_predictions_rbf <- predict(letter_classifier_rbf,
letters_test)

agreement_rbf <- letter_predictions_rbf == letters_test$letter

table(agreement_rbf)

prop.table(table(agreement_rbf))

```


```{r}

groceries_data <- read.transactions("C:\\Users\\harsh\\Desktop\\Introduction to Machine learning and Data Mining\\Practice 7\\groceries.csv", sep = ",") 

summary(groceries_data)

inspect(groceries_data[1:5])

itemFrequency(groceries_data[, 1:3])

itemFrequencyPlot(groceries_data, support = 0.1)

itemFrequencyPlot(groceries_data, topN = 20)

image(groceries_data[1:5])

image(sample(groceries_data, 100))

apriori(groceries_data)

groceryrules <- apriori(groceries_data, parameter = list(support =
0.006, confidence = 0.25, minlen = 2))

groceryrules

summary(groceryrules)

inspect(groceryrules[1:3])

inspect(sort(groceryrules, by = "lift")[1:5])

berryrules <- subset(groceryrules, items %in% "berries")

inspect(berryrules)

write(groceryrules, file = "groceryrules.csv",
sep = ",", quote = TRUE, row.names = FALSE)

groceryrules_df <- as(groceryrules, "data.frame")

str(groceryrules_df)

```
















