---
title: "Practicum-1"
output: pdf_document
---

```{r}

data <- read.table("glass.data",sep=',')
head(data)
str(data)

col_names <- c("id","RI","Na","Mg","Al","Si","K","Ca","Ba","Fe","Type")
colnames(data) <- col_names

head(data)

```


```{r}

h<-hist(data$RI, breaks=10, col="blue", xlab="Refractive Index",
   main="Histogram with Normal Curve")
xfit<-seq(min(data$RI),max(data$RI),length=40)
yfit<-dnorm(xfit,mean=mean(data$RI),sd=sd(data$RI))
yfit <- yfit*diff(h$mids[1:2])*length(data$RI)
lines(xfit, yfit, col="red", lwd=2)

```


```{r}
data1<-data

for (i in 2:10) {
mean_data <- mean(data[,i])
sd_data <- sd(data[,i])
zscore <- abs((mean_data-data[,i])/sd_data)
data1[which(!(zscore>2)),i] = NA
}
data1

```


```{r}
data2 <- data[-1]

normalize <- function(x){
  return(abs((mean(x)-x)/sd(x)))
}

data2 <- as.data.frame(lapply(data2[,1:9],normalize))
data2$Type <- data$Type
data2
summary(data2)


```


```{r}

set.seed(77654)

sample_1 <- sample.int(n = nrow(data2), size = floor(.20*nrow(data2)), replace = F)

validation_data <- data2[sample_1,]

training_data <- data2[-sample_1,]

```


```{r}

distance <- function(x,y){
  d <- 0
  for (i in 1:length(x)) {
    d <- d + (x[i]-y[i])^2
  }
  distance <- sqrt(d)
}

neighbours <- function(train,u){
  m <- nrow(train)
  ds <- numeric(m)
  q <- as.numeric(u[1:9])
  for (i in 1:m) {
    p <- train[i,1:9]
    ds[i] <- distance(p,q)
  }
  neighbours <- ds
}


k.closest <- function(neighbours,k){
  ordered.neighbours <- order(neighbours)
  k.closest <- ordered.neighbours[1:k]
}

Mode <- function(x){
  ux <- unique(x)
  ux[which.max(tabulate(match(x,ux)))]
}


knn <- function(train,unknown,k){
  neighbour <- neighbours(train, unknown)
  closest_neighbours <- k.closest(neighbour, k)
  knn <- Mode(data2$Type[closest_neighbours])
}

unknown <- c(1.51621,12.53,3.48,1.39,73.39,0.6,8.55,0.00,0.08)

unknown <- normalize(unknown)
unknown

test1 <- knn(data2,unknown,5)

```

